// Generated by gencpp from file diffbot_msgs/AngularVelocitiesStamped.msg
// DO NOT EDIT!


#ifndef DIFFBOT_MSGS_MESSAGE_ANGULARVELOCITIESSTAMPED_H
#define DIFFBOT_MSGS_MESSAGE_ANGULARVELOCITIESSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <diffbot_msgs/AngularVelocities.h>

namespace diffbot_msgs
{
template <class ContainerAllocator>
struct AngularVelocitiesStamped_
{
  typedef AngularVelocitiesStamped_<ContainerAllocator> Type;

  AngularVelocitiesStamped_()
    : header()
    , angular_velocities()  {
    }
  AngularVelocitiesStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angular_velocities(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::diffbot_msgs::AngularVelocities_<ContainerAllocator>  _angular_velocities_type;
  _angular_velocities_type angular_velocities;





  typedef boost::shared_ptr< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AngularVelocitiesStamped_

typedef ::diffbot_msgs::AngularVelocitiesStamped_<std::allocator<void> > AngularVelocitiesStamped;

typedef boost::shared_ptr< ::diffbot_msgs::AngularVelocitiesStamped > AngularVelocitiesStampedPtr;
typedef boost::shared_ptr< ::diffbot_msgs::AngularVelocitiesStamped const> AngularVelocitiesStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator1> & lhs, const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angular_velocities == rhs.angular_velocities;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator1> & lhs, const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diffbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62b2cae704bd641c35dea902c2913994";
  }

  static const char* value(const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62b2cae704bd641cULL;
  static const uint64_t static_value2 = 0x35dea902c2913994ULL;
};

template<class ContainerAllocator>
struct DataType< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diffbot_msgs/AngularVelocitiesStamped";
  }

  static const char* value(const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message that holds commanded angular joint velocity\n"
"Header header\n"
"\n"
"# Use an array of type float32 for the two wheel joint velocities.\n"
"# float32 is used instead of float64 because it is not supporte by Arduino/Teensy.\n"
"AngularVelocities angular_velocities\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: diffbot_msgs/AngularVelocities\n"
"# This is a message that holds commanded angular joint velocity\n"
"# Use an array of type float32 for the two wheel joint velocities.\n"
"# float32 is used instead of float64 because it is not supporte by Arduino/Teensy.\n"
"float32[] joint\n"
;
  }

  static const char* value(const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angular_velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngularVelocitiesStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diffbot_msgs::AngularVelocitiesStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angular_velocities: ";
    s << std::endl;
    Printer< ::diffbot_msgs::AngularVelocities_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocities);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFBOT_MSGS_MESSAGE_ANGULARVELOCITIESSTAMPED_H
