// Generated by gencpp from file diffbot_msgs/PIDStamped.msg
// DO NOT EDIT!


#ifndef DIFFBOT_MSGS_MESSAGE_PIDSTAMPED_H
#define DIFFBOT_MSGS_MESSAGE_PIDSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <diffbot_msgs/PID.h>

namespace diffbot_msgs
{
template <class ContainerAllocator>
struct PIDStamped_
{
  typedef PIDStamped_<ContainerAllocator> Type;

  PIDStamped_()
    : header()
    , pid()  {
    }
  PIDStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::diffbot_msgs::PID_<ContainerAllocator>  _pid_type;
  _pid_type pid;





  typedef boost::shared_ptr< ::diffbot_msgs::PIDStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diffbot_msgs::PIDStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PIDStamped_

typedef ::diffbot_msgs::PIDStamped_<std::allocator<void> > PIDStamped;

typedef boost::shared_ptr< ::diffbot_msgs::PIDStamped > PIDStampedPtr;
typedef boost::shared_ptr< ::diffbot_msgs::PIDStamped const> PIDStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diffbot_msgs::PIDStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diffbot_msgs::PIDStamped_<ContainerAllocator1> & lhs, const ::diffbot_msgs::PIDStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pid == rhs.pid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diffbot_msgs::PIDStamped_<ContainerAllocator1> & lhs, const ::diffbot_msgs::PIDStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diffbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diffbot_msgs::PIDStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diffbot_msgs::PIDStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diffbot_msgs::PIDStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76f54f0857a76c5e79d6f9203f257b96";
  }

  static const char* value(const ::diffbot_msgs::PIDStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76f54f0857a76c5eULL;
  static const uint64_t static_value2 = 0x79d6f9203f257b96ULL;
};

template<class ContainerAllocator>
struct DataType< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diffbot_msgs/PIDStamped";
  }

  static const char* value(const ::diffbot_msgs::PIDStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold the PID tuning values\n"
"Header header\n"
"\n"
"# Required only for the low level rosserial base_controller\n"
"# because rosserial doesn't support dynamic reconfigure\n"
"PID pid\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: diffbot_msgs/PID\n"
"# This is a message to hold the PID tuning values\n"
"# Required only for the low level rosserial base_controller\n"
"# because rosserial doesn't support dynamic reconfigure\n"
"float32 kp\n"
"float32 ki\n"
"float32 kd\n"
;
  }

  static const char* value(const ::diffbot_msgs::PIDStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PIDStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diffbot_msgs::PIDStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diffbot_msgs::PIDStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pid: ";
    s << std::endl;
    Printer< ::diffbot_msgs::PID_<ContainerAllocator> >::stream(s, indent + "  ", v.pid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFFBOT_MSGS_MESSAGE_PIDSTAMPED_H
