// Generated by gencpp from file drone_controller/MoveDroneWResponse.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_MOVEDRONEWRESPONSE_H
#define DRONE_CONTROLLER_MESSAGE_MOVEDRONEWRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct MoveDroneWResponse_
{
  typedef MoveDroneWResponse_<ContainerAllocator> Type;

  MoveDroneWResponse_()
    : command_status(false)  {
    }
  MoveDroneWResponse_(const ContainerAllocator& _alloc)
    : command_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _command_status_type;
  _command_status_type command_status;





  typedef boost::shared_ptr< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveDroneWResponse_

typedef ::drone_controller::MoveDroneWResponse_<std::allocator<void> > MoveDroneWResponse;

typedef boost::shared_ptr< ::drone_controller::MoveDroneWResponse > MoveDroneWResponsePtr;
typedef boost::shared_ptr< ::drone_controller::MoveDroneWResponse const> MoveDroneWResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::MoveDroneWResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::MoveDroneWResponse_<ContainerAllocator1> & lhs, const ::drone_controller::MoveDroneWResponse_<ContainerAllocator2> & rhs)
{
  return lhs.command_status == rhs.command_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::MoveDroneWResponse_<ContainerAllocator1> & lhs, const ::drone_controller::MoveDroneWResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "943f51d9faa4a44a232934ed3bd1b114";
  }

  static const char* value(const ::drone_controller::MoveDroneWResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x943f51d9faa4a44aULL;
  static const uint64_t static_value2 = 0x232934ed3bd1b114ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/MoveDroneWResponse";
  }

  static const char* value(const ::drone_controller::MoveDroneWResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool    command_status\n"
"\n"
;
  }

  static const char* value(const ::drone_controller::MoveDroneWResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveDroneWResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::MoveDroneWResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::MoveDroneWResponse_<ContainerAllocator>& v)
  {
    s << indent << "command_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_MOVEDRONEWRESPONSE_H
