// Generated by gencpp from file drone_controller/SetRefPoseResponse.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_SETREFPOSERESPONSE_H
#define DRONE_CONTROLLER_MESSAGE_SETREFPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct SetRefPoseResponse_
{
  typedef SetRefPoseResponse_<ContainerAllocator> Type;

  SetRefPoseResponse_()
    : update_status(false)  {
    }
  SetRefPoseResponse_(const ContainerAllocator& _alloc)
    : update_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _update_status_type;
  _update_status_type update_status;





  typedef boost::shared_ptr< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRefPoseResponse_

typedef ::drone_controller::SetRefPoseResponse_<std::allocator<void> > SetRefPoseResponse;

typedef boost::shared_ptr< ::drone_controller::SetRefPoseResponse > SetRefPoseResponsePtr;
typedef boost::shared_ptr< ::drone_controller::SetRefPoseResponse const> SetRefPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::SetRefPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::SetRefPoseResponse_<ContainerAllocator1> & lhs, const ::drone_controller::SetRefPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.update_status == rhs.update_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::SetRefPoseResponse_<ContainerAllocator1> & lhs, const ::drone_controller::SetRefPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f5872caddbe3a86c2173531b1fd3570";
  }

  static const char* value(const ::drone_controller::SetRefPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f5872caddbe3a86ULL;
  static const uint64_t static_value2 = 0xc2173531b1fd3570ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/SetRefPoseResponse";
  }

  static const char* value(const ::drone_controller::SetRefPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  update_status\n"
;
  }

  static const char* value(const ::drone_controller::SetRefPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.update_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRefPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::SetRefPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::SetRefPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "update_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_SETREFPOSERESPONSE_H
