// Generated by gencpp from file drone_controller/SetRefPoseRequest.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROLLER_MESSAGE_SETREFPOSEREQUEST_H
#define DRONE_CONTROLLER_MESSAGE_SETREFPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_controller
{
template <class ContainerAllocator>
struct SetRefPoseRequest_
{
  typedef SetRefPoseRequest_<ContainerAllocator> Type;

  SetRefPoseRequest_()
    : x_ref_w(0.0)
    , y_ref_w(0.0)
    , alt_ref_w(0.0)
    , yaw_ref_w(0.0)  {
    }
  SetRefPoseRequest_(const ContainerAllocator& _alloc)
    : x_ref_w(0.0)
    , y_ref_w(0.0)
    , alt_ref_w(0.0)
    , yaw_ref_w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_ref_w_type;
  _x_ref_w_type x_ref_w;

   typedef double _y_ref_w_type;
  _y_ref_w_type y_ref_w;

   typedef double _alt_ref_w_type;
  _alt_ref_w_type alt_ref_w;

   typedef double _yaw_ref_w_type;
  _yaw_ref_w_type yaw_ref_w;





  typedef boost::shared_ptr< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRefPoseRequest_

typedef ::drone_controller::SetRefPoseRequest_<std::allocator<void> > SetRefPoseRequest;

typedef boost::shared_ptr< ::drone_controller::SetRefPoseRequest > SetRefPoseRequestPtr;
typedef boost::shared_ptr< ::drone_controller::SetRefPoseRequest const> SetRefPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_controller::SetRefPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_controller::SetRefPoseRequest_<ContainerAllocator1> & lhs, const ::drone_controller::SetRefPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x_ref_w == rhs.x_ref_w &&
    lhs.y_ref_w == rhs.y_ref_w &&
    lhs.alt_ref_w == rhs.alt_ref_w &&
    lhs.yaw_ref_w == rhs.yaw_ref_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_controller::SetRefPoseRequest_<ContainerAllocator1> & lhs, const ::drone_controller::SetRefPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb836e8feb393aeb4dfa49d7e6234086";
  }

  static const char* value(const ::drone_controller::SetRefPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb836e8feb393aebULL;
  static const uint64_t static_value2 = 0x4dfa49d7e6234086ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_controller/SetRefPoseRequest";
  }

  static const char* value(const ::drone_controller::SetRefPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_ref_w\n"
"float64 y_ref_w\n"
"float64 alt_ref_w\n"
"float64 yaw_ref_w\n"
;
  }

  static const char* value(const ::drone_controller::SetRefPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_ref_w);
      stream.next(m.y_ref_w);
      stream.next(m.alt_ref_w);
      stream.next(m.yaw_ref_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRefPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_controller::SetRefPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_controller::SetRefPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_ref_w: ";
    Printer<double>::stream(s, indent + "  ", v.x_ref_w);
    s << indent << "y_ref_w: ";
    Printer<double>::stream(s, indent + "  ", v.y_ref_w);
    s << indent << "alt_ref_w: ";
    Printer<double>::stream(s, indent + "  ", v.alt_ref_w);
    s << indent << "yaw_ref_w: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_ref_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROLLER_MESSAGE_SETREFPOSEREQUEST_H
