(cl:defpackage diffbot_msgs-msg
  (:use )
  (:export
   "<ANGULARVELOCITIES>"
   "ANGULARVELOCITIES"
   "<ANGULARVELOCITIESSTAMPED>"
   "ANGULARVELOCITIESSTAMPED"
   "<ENCODERS>"
   "ENCODERS"
   "<ENCODERSSTAMPED>"
   "ENCODERSSTAMPED"
   "<PID>"
   "PID"
   "<PIDSTAMPED>"
   "PIDSTAMPED"
   "<WHEELSCMD>"
   "WHEELSCMD"
   "<WHEELSCMDSTAMPED>"
   "WHEELSCMDSTAMPED"
  ))

